# Generated by Django 5.2.5 on 2025-11-03 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('location', models.CharField(help_text='Area/Estate/Building', max_length=200)),
                ('interest_level', models.CharField(choices=[('very_interested', 'Very Interested'), ('interested', 'Interested'), ('neutral', 'Neutral'), ('not_interested', 'Not Interested'), ('converted', 'Converted to Customer')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to=settings.AUTH_USER_MODEL)),
                ('preferred_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakcomapp.internetpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='zakcomapp.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('installed', 'Installed'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('contract_duration', models.IntegerField(default=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakcomapp.customer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zakcomapp.internetpackage')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('visit_time', models.TimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(help_text='Area/Estate/Building visited', max_length=200)),
                ('outcome', models.CharField(choices=[('interested', 'Showed Interest'), ('not_interested', 'Not Interested'), ('follow_up', 'Needs Follow-up'), ('closed_sale', 'Closed Sale'), ('not_home', 'Not Home'), ('wrong_location', 'Wrong Location')], max_length=20)),
                ('feedback', models.TextField(help_text='Customer feedback and comments')),
                ('price_concern', models.BooleanField(default=False)),
                ('coverage_concern', models.BooleanField(default=False)),
                ('has_existing_provider', models.BooleanField(default=False)),
                ('existing_provider_name', models.CharField(blank=True, max_length=100)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='zakcomapp.prospect')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_count', models.IntegerField()),
                ('target_visits', models.IntegerField(default=0)),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('achieved_count', models.IntegerField(default=0)),
                ('achieved_visits', models.IntegerField(default=0)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sales_person', 'month')},
            },
        ),
    ]
